name: image creator CI

on: [ push ]

jobs:
  build:
    name: Create a machine image
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      NODE_ENV:  ${{ secrets.NODE_ENV }}
      CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
      AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Add an .env file
        run: |
          touch .env ./backend
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "TOPIC=${{ secrets.CHATGPT_KEY }}" >> .env
          echo "DOMAIN=${{ secrets.MONGODB_URI }}" >> .env
          echo "EXPIRY=${{ secrets.AMADEUS_CLIENT_ID}}" >> .env
          echo "EXPIRY=${{ secrets.AMADEUS_CLIENT_SECRET}}" >> .env

      - name: Zip the application
        run: |
          zip -r webapp.zip ./backend
      
      - name: Install npm dependencies
        run: npm install   --prefix ./backend/ 

      - name: Setting up Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
          unzip -o packer_1.7.3_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/

      - name: Initializing Packer
        run: packer init ./packer/backend/main.pkr.hcl

      - name: Building the Image
        run: packer build -var 'project_id=${{ secrets.PROJECT_ID }}' -var 'zone=${{ secrets.ZONE }}' ./packer/backend/main.pkr.hcl      

